Ejercicio 11: Señala la respuesta correcta sobre las excepciones:

a. Una sentencia try no puede estar dentro de un bloque de otra secuencia try b.	==> Falso

b. Un bloque try va seguido por un único bloque catch								==> Falso

c. Cada bloque catch especifica el tipo de excepción que puede atrapar y contiene
un manejador de excepciones.														==> Verdadero

d. El bloque finally se ejecuta si no ocurre la excepción.							==> Falso